{{- if .Values.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  apiKeys: {{ .Values.apiKeys | quote }}
{{- end }}
